var students = [
  { fullName: "John Doe", grade: 85 },
  { fullName: "Jane Doe", grade: 90 },
  { fullName: "Jim Smith", grade: 77 },
  { fullName: "Sarah Johnson", grade: 95 },
  { fullName: "Tom Brown", grade: 80 },
  { fullName: "Emma Wilson", grade: 88 },
  { fullName: "Michael Davis", grade: 75 },
  { fullName: "Emily Clark", grade: 92 },
  { fullName: "William Martinez", grade: 78 },
  { fullName: "Isabella Anderson", grade: 87 },
  { fullName: "Jacob Thompson", grade: 84 },
  { fullName: "Olivia Harris", grade: 89 },
  { fullName: "Ethan Young", grade: 76 },
  { fullName: "Ava Allen", grade: 95 },
  { fullName: "Noah King", grade: 82 },
  { fullName: "Sophia Wright", grade: 90 },
  { fullName: "Mason Baker", grade: 79 },
  { fullName: "Aria Nelson", grade: 86 },
  { fullName: "Eli Adams", grade: 83 },
  { fullName: "Avery Cooper", grade: 88 },
];
